sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master
    - 2.1

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pushd $TRAVIS_BUILD_DIR
  - source scripts/setup.sh || exit 1


script:
  - npm run build

after_success:
  # Here is where all things you want to do after build success is done

cache:
  # improve build time cache stuffs that do not change occasionally eg. node_modules
  directories:
    - node_modules/

notifications:
  email:
    recipients:
    - rajeyw@gmail.com
    on_failure: always
    on_success: always
    
  slack:
    on_failure: always
    on_success: always
